#!/usr/bin/env python
import json, sys, os, re, shutil, shlex, getopt, platform
from distutils.util import strtobool
from subprocess import call, check_output, CalledProcessError

SCRIPT_ROOT_DIR = os.path.join(os.path.expanduser("~"), '.vimpkg')
VIM_ROOT_DIR = os.path.join(os.path.expanduser("~"), '.vim')
SRC_DIR = os.path.join(SCRIPT_ROOT_DIR, 'src')
#BIN_DIR = os.path.join(SCRIPT_ROOT_DIR, 'bin')
GBL = 'global'
DPND = 'depends-on'
NAME = 'name'
TRG_DIR = 'install-target'
PKG_URL = 'pkg-url'
PKGS = 'packages'
RECIPE = 'recipe'
VIM_CONFIG = None
OS = 'os'
HOST_OS = platform.system().lower()
VIM_CONFIG_PATH = os.path.join(SCRIPT_ROOT_DIR, 'vim_config.json')

####### CMD LINE FLAGS #######
ASSUME_YES = False


class PkgItem(object):
    def get_recipe(self):
        recipe = []
        if HOST_OS in self.recipe:
            recipe = self.recipe[HOST_OS]
        elif 'all' in self.recipe:
            recipe = self.recipe['all']
        if self.recipe and not recipe:
            if not report_fail('No recipe for your OS'):
                sys.exit(1)
        return recipe

class Dependency(PkgItem):
    def __init__(self, name='dep', recipe={}):
        self.name = name
        self.recipe = recipe

    def to_dict(self):
        # Convert python variable names to json variable names
        return {k.replace('_', '-'): v for k,v in self.__dict__.items()}

    @staticmethod
    def dict_to_dep(d):
        return Dependency(d[NAME], d[RECIPE])


class VimPackage(PkgItem):
    def __init__(self, pkg_url='', name='', depends_on=[], recipe={}):
        self.pkg_url = pkg_url
        self.name = name
        self.depends_on = depends_on
        self.recipe = recipe

    def to_dict(self):
        # Convert python variable names to json variable names
        d = {k.replace('_', '-'): v for k,v in self.__dict__.items()}
        deps = [ dep.to_dict() for dep in self.depends_on ]
        d[DPND] = deps
        return d

    @staticmethod
    def dict_to_vimpkg(d):
        deps = [ Dependency.dict_to_dep(dep) for dep in d[DPND] ]
        return VimPackage(d[PKG_URL], d[NAME], deps, d[RECIPE])


def load_vim_config(file_path=VIM_CONFIG_PATH):
    global VIM_CONFIG
    json_file = open(file_path).read()
    VIM_CONFIG = json.loads(json_file)

def get_install_target():
    path = VIM_CONFIG[GBL][TRG_DIR]
    path = path.replace('~', os.path.expanduser('~'))
    return path

def get_global_requirements():
    return [ req[NAME] for req in VIM_CONFIG[GBL][DPND] ]

def get_vimpkg(git_url):
    pkg = [ p for p in VIM_CONFIG[PKGS] if p[PKG_URL] == git_url ]
    if pkg:
        return VimPackage.dict_to_vimpkg(pkg[0])
    else:
        return None

def status_update(pkg_name):
    print '\nCloning, configuring, and installing `' + pkg_name + '`'

def install_pkg(vimpkg):
    status_update(vimpkg.name)
    install_target = get_install_target()
    # Install dependencies of package
    install_dependencies(vimpkg.name, vimpkg.depends_on)
    # Clone the plugin and run any post-install commands
    recipe = vimpkg.get_recipe()
    __install_pkg(vimpkg.name, vimpkg.pkg_url, install_target, recipe)
    # Change back to the DIR containing this script
    os.chdir(SCRIPT_ROOT_DIR)

def get_pkg_name(git_url):
    vimpkg = get_vimpkg(git_url)
    if vimpkg:
        return vimpkg.name
    if ASSUME_YES:
        return get_pkg_name_from_url(git_url)
    pkg_name = raw_input('Enter a name for package `' + git_url + '` (<ENTER> for automatic naming):  ')
    if not pkg_name:
        pkg_name = get_pkg_name_from_url(git_url)
    return pkg_name

def add_pkg(pkg_name, git_url):
    vimpkg = VimPackage(pkg_url=git_url)
    vimpkg.name = pkg_name
    install_target = get_install_target()

    if os.path.exists(os.path.join(install_target, pkg_name)): # or \
        print 'Skipping installed package `' + pkg_name + '`'
        print 'To re-install `' + pkg_name + '` run:' \
                + '\n\t`apt-vim remove ' + pkg_name + '`' \
                + '\n\t`apt-vim install ' + git_url + '`'
        sys.exit(0)

    # Get dependencies of package
    depends = get_depend(pkg_name)
    vimpkg.depends_on = depends

    msg = 'Any commands to run after cloning `' + pkg_name + '`?'
    post_install_recipe = get_recipe(msg)
    if post_install_recipe:
        vimpkg.recipe[HOST_OS] = post_install_recipe
    return vimpkg

def clone_pkg(git_url, pkg_name=None):
    if not pkg_name:
        pkg_name = get_pkg_name_from_url(git_url)
    try:
        call(['git', 'clone', git_url, pkg_name])
    except:
        report_fail('Failed to clone `' + pkg_name + '`')

def __install_pkg(pkg_name, git_url, install_target, commands=[]):
    # Change to directory with vim plugins
    os.chdir(install_target)
    clone_pkg(git_url, pkg_name)
    os.chdir(pkg_name)
    if not exe_shell_commands(commands):
        report_fail('Failed to intall ' + pkg_name)

def install_dependencies(pkg_name, dependencies=[]):
    if dependencies:
        # Change to directory with dependency source
        os.chdir(SRC_DIR)
        if not os.path.exists(pkg_name):
            os.makedirs(pkg_name)
        os.chdir(pkg_name)

    for dep in dependencies:
        if not check_requirements([dep.name]):
            commands = dep.get_recipe()
            if not exe_shell_commands(commands):
                report_fail('Failed to intall ' + pkg_name)
        else:
            print '`' + dep.name + '` already in PATH'

def user_confirm(msg=None):
    if msg is None:
        msg = 'Do you wish to continue anyways?'
    msg += ' [y|N]:  '
    num_tries = 0
    while num_tries < 3:
        try:
            user_choice = raw_input(msg).strip().lower()
            if strtobool(user_choice):
                return True
            return False
        except:  # Invalid option, retry
            print 'Invalid option. Please enter `Y` or `N` only'
            num_tries += 1
    sys.exit(1)

def report_fail(fail_msg=None, confirm_msg=None, confirm_continue=True):
    if fail_msg is None:
        fail_msg = 'Something went wrong...\n'
    print fail_msg
    if confirm_continue:
        return user_confirm(confirm_msg)

def add_overwrite(pkg_name, git_url):
    install_target = get_install_target()
    if user_confirm('Package `' + pkg_name + '` already exists. Do you wish to overwrite?'):
        # Delete plugin and its dependencies/src
        remove_pkg(pkg_name, install_target)
        # Delete package from json
        VIM_CONFIG[PKGS] = remove_pkg_ref(pkg_name)
        return True
    return False

def remove_pkg(pkg_name, install_target):
    remove_pkg_src(pkg_name)
    remove_pkg_plugin(pkg_name, install_target)
    #TODO: check all dependencies related to pkg_name
    # If no other package depends on this binary, remove it
    #if pkg_name not in [ dep[NAME] for dep in [p[DPND] for p in remove_pkg_ref(git_url, vim_config)]] ]:
        #remove_pkg_bin(pkg_name)

def remove_dir(dir):
    if os.path.exists(dir):
        shutil.rmtree(dir)

#def remove_pkg_bin(pkg_name):
    #dir = os.path.join(BIN_DIR, pkg_name)
    #remove_dir(dir)

def remove_pkg_src(pkg_name):
    dir = os.path.join(SRC_DIR, pkg_name)
    remove_dir(dir)

def remove_pkg_ref(pkg_name):
    return [ p for p in VIM_CONFIG[PKGS] if pkg_name not in p[PKG_URL] ]

def remove_pkg_plugin(pkg_name, install_target):
    dir = os.path.join(install_target, pkg_name)
    remove_dir(dir)

def get_depend(pkg_name='this plugin'):
    depends = []
    if user_confirm('Does ' + pkg_name + ' have any Dependencies?'):
        i = 1;
        dep_name = raw_input('Name for dependency ' + str(i) + ':  ')
        while dep_name != "":
            depends.append(__get_depend(dep_name))
            i += 1
            dep_name = raw_input('Name for dependency ' + str(i) + ':  ')
    return depends

def __get_depend(name):
    dep = Dependency(name)
    recipe = get_recipe()
    # Only save the recipe if there is a recipe to save...
    if recipe:
        dep.recipe[HOST_OS] = recipe
    return dep

def get_recipe(msg=None):
    if msg is None:
        return __get_recipe()
    if user_confirm(msg):
        return  __get_recipe()
    else:
        return []

def __get_recipe():
    commands = []
    print '\nEnter commands one line at a time. ' + \
            'Terminate commands with an empty line.'
    i = 1
    command = raw_input('Command ' + str(i) + ': ')
    while command != "":
        i += 1
        commands.append(command)
        command = raw_input('Command ' + str(i) + ': ')
    return commands

def save_vim_config(vimpkg=None, file_path=None):
    if file_path is None:
        file_path = os.path.join(SCRIPT_ROOT_DIR, 'vim_config.json')
    try:
        with open(file_path) as f:
            data = json.load(f)

        if vimpkg:
            VIM_CONFIG[PKGS].append(vimpkg.to_dict())
        data[PKGS] = VIM_CONFIG[PKGS]
        with open(file_path, 'w') as f:
            json.dump(data, f, sort_keys=True, indent=4, separators=(',', ': '))
    except:
        print 'failed to write ' + file_path
        sys.exit(1)

def get_pkg_name_from_url(git_url):
    pkg_regex = re.compile(r'.*\/([^\/]+).git$')
    match = pkg_regex.match(git_url)
    if match:
        return match.group(1)
    return None

def check_requirements(requirements=None):
    if requirements is None:
        return True
    for req in requirements:
        if not call_silent(['which', req]):
            return False
    return True

def valid_url(url):
    regex = re.compile(
            r'^(?:http|ftp)s?://' # http:// or https:// or ftp:// or ftps://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|' #domain...
        r'localhost|' #localhost...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' # ...or ip
        r'(?::\d+)?' # optional port
        r'(?:/?|[/?]\S+)$', re.IGNORECASE)
    match = regex.search(url)
    return True if match else False

def call_silent(command):
    try:
        with open(os.devnull, 'wb') as devnull:
            exit_code = call(command, stdout=devnull)
            if exit_code:
                return False
    except CalledProcessError:
        return False
    return True

def usage():
    pass

def exe_shell_commands(commands=None):
    if commands is None:
        commands = []
    for com in commands:
        com = com.replace('~', os.path.expanduser("~"))
        try:
            if 'cd' in com:
                os.chdir(shlex.split(com)[1])
            else:
                call(shlex.split(com))
        except:
            return report_fail('Command `' + com + '` failed.')
    return True

def init():
    if not os.path.exists(VIM_ROOT_DIR):
        os.makedirs(VIM_ROOT_DIR)

    if not os.path.exists(SCRIPT_ROOT_DIR):
        os.makedirs(SCRIPT_ROOT_DIR)
    # Copy the config file to ~/.vimpkg/vim_config.json
    shutil.copy('vim_config.json', VIM_CONFIG_PATH)
    load_vim_config()

    bundle_path = os.path.join(os.path.expanduser("~"), '.vim/bundle')
    if os.path.lexists(bundle_path):
        dest_path = bundle_path + '.bak'
        shutil.move(bundle_path, dest_path)
    install_target = get_install_target()
    if not os.path.exists(install_target):
        os.makedirs(install_target)
    os.symlink(install_target, bundle_path)


    #if not os.path.exists(BIN_DIR):
        #os.makedirs(BIN_DIR)
    if not os.path.exists(SRC_DIR):
        os.makedirs(SRC_DIR)

    missing_deps = []
    deps = VIM_CONFIG[GBL][DPND]
    for dep in deps:
        dep = Dependency.dict_to_dep(dep)
        if not check_requirements([dep.name]):
            if not dep.get_recipe() or  \
                    not exe_shell_commands(dep.get_recipe()):
                missing_deps.append(dep.name)
    return missing_deps

def get_urls_from_list(check_list):
    urls = []
    for item in check_list:
        if valid_url(item):
            urls.append(item)
    return urls

def get_installed_pkgs():
    return os.listdir(os.path.join(VIM_ROOT_DIR, 'bundle'))

def __handle_install(argv, options, git_urls):
    global ASSUME_YES
    if not argv or not git_urls:
        # No options and no git URL passed
        for pkg in [ p for p in VIM_CONFIG[PKGS] if  \
                p[NAME] not in get_installed_pkgs() ]:
            vimpkg = VimPackage.dict_to_vimpkg(pkg)
            if ASSUME_YES or user_confirm('Install `' + vimpkg.name + '`?'):
                install_pkg(vimpkg)
        return
    #TODO process cmd options, then install
    for git_url in git_urls:
        vimpkg = get_vimpkg(git_url)
        pkg_name = get_pkg_name(git_url)
        if not vimpkg:
            vimpkg = add_pkg(pkg_name, git_url)
            save_vim_config(vimpkg, VIM_CONFIG_PATH)
        install_pkg(vimpkg)

def __handle_add(argv, options, git_urls):
    install_target = get_install_target()
    for git_url in git_urls:
        pkg_name = get_pkg_name(git_url)
        if git_url in [ p[PKG_URL] for p in VIM_CONFIG[PKGS] ]:
            if not add_overwrite(pkg_name, git_url):
                continue
        vimpkg = add_pkg(pkg_name, git_url)
        save_vim_config(vimpkg, VIM_CONFIG_PATH)

def __handle_remove(argv, options, git_urls):
    global ASSUME_YES
    install_target = get_install_target()
    if not git_urls:
        report_fail('No package URL specified. Exiting', confirm_continue=False)
        sys.exit(1)
    #TODO process cmd options
    for git_url in git_urls:
        pkg_name = get_pkg_name_from_url(git_url)
        msg = 'Confirm remove package `' + pkg_name + '`'
        if ASSUME_YES or user_confirm(msg):
            remove_pkg(pkg_name, install_target)
            VIM_CONFIG[PKGS] = remove_pkg_ref(pkg_name)
            save_vim_config(file_path=VIM_CONFIG_PATH)
            print 'Successfully removed package `' + pkg_name + '`'
        else:
            print 'Skipped removal of `' + pkg_name +'`'

def __handle_update(argv, options, git_urls):
    global ASSUME_YES
    install_target = get_install_target()
    if not git_urls:  # If no urls provided, assume updating all packages in vim_config
        git_urls = [ p[PKG_URL] for p in VIM_CONFIG[PKGS] ]
        if not git_urls:
            report_fail('No package URL specified. Exiting', confirm_continue=False)
            sys.exit(1)
    for git_url in git_urls:
        vimpkg = get_vimpkg(git_url)
        pkg_name = vimpkg.name
        #TODO process cmd options
        msg = 'Confirm update package `' + pkg_name + '`'
        if ASSUME_YES or user_confirm(msg):
            remove_pkg(pkg_name, install_target)
            install_pkg(vimpkg)
            print 'Successfully updated package `' + pkg_name + '`'
        else:
            print 'Skipped updating package `' + pkg_name +'`'


MODES = { 'install': __handle_install, 'remove': __handle_remove, \
        'update': __handle_update, 'add': __handle_add }

def process_cmd_args():
    argv = sys.argv[1:]
    mode = argv[0].lower()
    if mode not in MODES:
        usage()
        sys.exit()
    else:
        options, remainder = getopt.getopt(argv[1:], 'y', ['assume-yes'])
        for opt,arg in options:
            if opt in ('-y, --assume-yes'):
                global ASSUME_YES
                ASSUME_YES = True
        git_urls = get_urls_from_list(remainder)
        MODES[mode](argv[1:], options, git_urls)

def usage():
    print 'Valid modes: ', str(MODES.keys().sort()), '\n'

def main():
    missing_dependencies = init()
    if missing_dependencies:
        print 'Cannot proceed. Missing the following dependencies that could' \
                + ' not be automatically insatlled:\n' \
                + str(missing_dependencies)
        sys.exit(1)
    load_vim_config()
    process_cmd_args()
    print 'Completed successfully!'


if __name__ == '__main__':
    main()
